### ISSUE TITLE
example code for whale client doesnt work

### ISSUE THREAD

**Issue by Bloctans** [mrwhale-io/mrwhale#49]
i entered the id and frontend key, my bot went online, but when i said ping it did nothing, the on messages function doesnt even work, why?

**Comment by DybaTubeYT1** [comment]
what is userid and frontend thats my question i am trying to figure out

**Comment by Bloctans** [comment]
frontend is in your cookies
user id can be found in your avatar image link

**Comment by DybaTubeYT1** [comment]
Where?

https://i2.wp.com/s.gjcdn.net/img/no-avatar-3.png?ssl=1

**Comment by DybaTubeYT1** [comment]
Failed request [Join user notification channel]. Reattempt in 1000 ms

why I am getting this?

**Comment by DybaTubeYT1** [comment]
https://m.gjcdn.net/user-avatar/200/6565263-crop498_44_898_444-3cvteuik-v4.webp
help where userid

**Comment by DybaTubeYT1** [comment]
bruh it didnt worked too

**Comment by Bloctans** [comment]
its the 6565263 part of the pfp

**Comment by DybaTubeYT1** [comment]
Ik i found it but why when i type ping nothing works

Em qui, 31 de mar de 2022 5:09 PM, Bloctans ***@***.***>
escreveu:

**Comment by Bloctans** [comment]
why
